apiVersion: v1
kind: Service
metadata:
  name: hellok8s-app
  namespace: hellok8s-app-ns
spec:
  type: ClusterIP
  selector:
    app: hellok8s-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s-app
  namespace: hellok8s-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellok8s-app
  template:
    metadata:
      labels:
        app: hellok8s-app
    spec:
      containers:
        - name: hellok8s-app
          image: docker.io/thecodealchemist/hello-k8s-app:0.0.1
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 8080
